project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Apps"
    background: "#23102B"
    foreground: "#9F69C8"
    search: false
    pinned: true
    collapse: true
    tools-collapse: true
    left:
      - text: "Datos"
        href: https://bastianolea.github.io/datos_sociales/
      - text: "Blog"
        href: https://bastianolea.rbind.io/blog/
      - text: "Tutoriales"
        href: https://bastianolea.rbind.io/categories/tutoriales/
      - text: "Yo"
        href: https://bastianolea.rbind.io/about/
      - text: "Contacto"
        href: https://bastianolea.rbind.io/contacto/
    tools:
      - icon: globe
        href: https://bastianolea.rbind.io
      - icon: twitter
        href: https://bsky.app/profile/bastianolea.rbind.io
      - icon: github
        href: https://github.com/bastianolea?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/bastianolea/

format:
  html:
    toc: false
    include-after-body: goatcounter.html



