project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Apps"
    background: "#23102B"
    foreground: "#9F69C8"
    search: false
    pinned: true
    collapse: true
    tools-collapse: true
    left:
      - text: "Blog"
        href: https://bastianolea.rbind.io/blog/
      - text: "Datos"
        href: https://bastianolea.github.io/datos_sociales/
      - text: "Aprende R"
        href: https://bastianolea.github.io/aprende_r/
      - text: "Acerca de"
        href: https://bastianolea.rbind.io
    tools:
      - icon: globe
        href: https://bastianolea.rbind.io
      - icon: twitter
        href: https://bsky.app/profile/bastianolea.rbind.io
      - icon: github
        href: https://github.com/bastianolea?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/bastianolea/
      - icon: envelope
        href: https://bastianolea.rbind.io/contacto/

format:
  html:
    toc: false



